spring:
  datasource:
    url: jdbc:mysql://localhost:3306/friday?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    removeAbandonedTimeout: 1800
    maxWait: -1
    maxActive: 20
    logAbandoned: true
    initialSize: 0
    filters: stat
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
  thymeleaf:
    check-template: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  http:
    encoding:
      force: true
      enabled: true
    multipart:
      maxFileSize: 1024Mb
      maxRequestSize: 1024Mb

server:
  tomcat:
    uri-encoding: UTF-8

# log_config   DEBUG    ERROR    INFO    WARN
logging:
  level:
    root: error
    com:
      zx:
        system: DEBUG
